# Ce StatefulSet déploie une instance unique de la base de données PostgreSQL en utilisant l'image postgres:15-alpine.
apiVersion: apps/v1            
kind: StatefulSet              
metadata:
  name: db-statefulset         
spec:
  selector:
    matchLabels:
      app: db                  
  serviceName: db-service      # Nom du service utilisé pour accéder aux pods du StatefulSet
  replicas: 1                  
  template:
    metadata:
      labels:
        app: db                
    spec:
      containers:
      - name: db
        image: postgres:15-alpine 
        envFrom:
          - secretRef:
              name: db-secret   # Référence au Secret contenant les informations d'identification de la base de données
          - configMapRef:
              name: db-configmap  # Référence au ConfigMap contenant les configurations de la base de données
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data   
          mountPath: /var/lib/postgresql/data  
      volumes:
      - name: postgres-data     
        persistentVolumeClaim:
          claimName: db-pvc     