apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Ajustar según ecesidades de almacenamiento
  storageClassName: standard  # Asegurarse de que esta clase de almacenamiento está disponible en el clúster
