# Namespace
namespace: "prod"

ingress:
  name: "ingress"
  fastapiHostname: "devops-fastapi-prod.**.**" # Fill with Hostname

# FastAPI app variables
fastapiApp:
  replicas: 3
  name: "fastapi-app"
  image: "" # Fill with the correct image
  containerPort: 8000

fastapiService:
  name: "fastapi-service"

fastapiHpa:
  name: "fastapi-hpa"
  minReplicas: 5
  maxReplicas: 10
  averageUtilization: 70

clusterIssuer:
  name: "cluster-issuer"
